stages:
  - build

image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKERHUB_USERNAME: "lbbniu-1680322476594"
  CODING_REGISTRY: lbbniu-docker.pkg.coding.net/docker/lbbniu

services:
  - docker:20.10.16-dind

before_script:
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

build_and_push:
  stage: build
  script:
    - docker build -t $CODING_REGISTRY/frontend:$CI_COMMIT_SHORT_SHA ./frontend
    - docker push $CODING_REGISTRY/frontend:$CI_COMMIT_SHORT_SHA
    - docker build -t $CODING_REGISTRY/backend:$CI_COMMIT_SHORT_SHA ./backend
    - docker push $CODING_REGISTRY/backend:$CI_COMMIT_SHORT_SHA
