frontend:
  image: lbbniu-docker.pkg.coding.net/docker/lbbniu/frontend
  tag: latest
  autoscaling:
    averageUtilization: 50

backend:
  image: lbbniu-docker.pkg.coding.net/docker/lbbniu/backend
  tag: latest
  autoscaling:
    averageUtilization: 50

database:
  enabled: false
  uri: 10.10.10.10
  username: external_postgres
  password: external_postgres
