frontend:
  image: lbbniu-docker.pkg.coding.net/docker/lbbniu/frontend
  tag: 789a5b9
  autoscaling:
    averageUtilization: 90
backend:
  image: lbbniu-docker.pkg.coding.net/docker/lbbniu/backend
  tag: 789a5b9
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
